services:
  cipta-portfolio:
    image: ghcr.io/ciptacoding/ciptadwipajaya.id:latest
    container_name: ciptadwipajaya.id
    restart: unless-stopped
    ports:
      - "3000:80"   # sesuaikan port (3000 = contoh)